spring:
  application:
    name: backend
  mail:
    host: smtp.naver.com
    port: 465
    username: ${NAVER_MAIL_USERNAME}
    password: ${NAVER_MAIL_PASSWORD}

  auth:
    jwt:
      secretKey: ${JWT_SECRET_KEY}
      access:
        header: ${JWT_ACCESS_HEADER}

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: MySQL8Dialect

springdoc:
  swagger-ui:
    path: ${SWAGGER_UI}
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: ${API_DOCS}
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8